config/routes.rb
Dlp::Application.routes.draw do
  resources :search_suggestions

  devise_for :users, :controllers => {sessions: 'sessions'}
  root :to => 'welcome#index'
  resources :worker_profiles

  get "/new_moving_job" => "jobs#new_moving_job", as: :new_moving_job
  get "/new_painting_job" => "jobs#new_painting_job", as: :new_painting_job
  get "/new_gardening_job" => "jobs#new_gardening_job", as: :new_gardening_job
  get "/new_other_job" => "jobs#new_other_job", as: :new_other_job
  get "/user_sign_up" => "users#new", as: :user_sign_up

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

  match '/jobs/:id/jobdispatch' => 'jobs#jobdispatch', :as => :job_jobdispatch
  match '/jobs/:id/addworker/:id' => 'jobs#addworker', :as => :job_addworker

  resources :users, :only => [:show]
  match "welcome/about" => "welcome#about", :as => :about
  match "welcome/contact" => "welcome#contact", :as => :contact
  match "welcome/faq" => "welcome#faq", :as => :faq
  match "welcome/howtohire" => "welcome#howtohire", :as => :howtohire

  match '/admin/jobs/:id/worker_profiles' => 'admin/jobs#worker_profiles', :as => :admin_job_workers

  # resources :identifications


  # resources :items

  # resources :reviews


  # resources :wages


  resources :jobs


  resources :employer_profiles


  # resources :dues


  # resources :referrals






end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  def dispatches
    Job.where(:dispatcher_id => self.id)
  end

  def receives
    Job.where(:receiver_id => self.id)
  end
end

app/models/due.rb
class Due < ActiveRecord::Base
  attr_accessible :amount, :last_paid, :worker_profile_id

  belongs_to :worker_profile
end

app/models/identification.rb
class Identification < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :worker_profiles
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :worker_profiles
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name

has_and_belongs_to_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :address, :cross_street, :date_of_job, :description, :dispatcher_id, :duration, :employer_profile_id, :english_level, :estimate, :estimate_accepted, :estimate_amount, :frequency, :job_status, :kind, :num_of_workers, :on_going, :one_time, :payment, :phone_kind, :phone_number, :receiver_id, :referred_by, :will_pick_up, :requirement, :employer_first_name, :employer_last_name
  belongs_to :employer_profile
  belongs_to :dispatcher, :class_name => AdminUser
  belongs_to :receiver, :class_name => AdminUser
  has_and_belongs_to_many :items
  has_and_belongs_to_many :worker_profiles
  has_and_belongs_to_many :wages
  has_one :review


  def has_workers
    !self.worker_profiles.empty?
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :url, :user_id

  belongs_to :user
end

app/models/referral.rb
class Referral < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :name
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :answer1, :answer2, :answer3, :answer4, :answer5, :job_id, :prompt1, :prompt2, :prompt3, :prompt4, :prompt5
belongs_to :job
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :worker_profiles
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :worker_profiles
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :timeoutable, :validatable
    attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_id, :profile_type
  belongs_to :profile, polymorphic: true
  has_many :photos

  def has_profile
    !self.profile_type.nil?
  end

  def has_photos
    !self.photos.empty?
  end

  def is_worker
    self.profile_type == "WorkerProfile"
  end

  def is_employer
    self.profile_type == "EmployerProfile"
  end

  def has_jobs
    !self.profile.jobs.empty?
  end
end

app/models/wage.rb
class Wage < ActiveRecord::Base
  attr_accessible :base_amount, :name, :ot_amount
  has_and_belongs_to_many :jobs
end

app/controllers/jobs_controller.rb
class JobsController < InheritedResources::Base
  before_filter :authenticate_user!, :except => [:new, :new_moving_job, :new_painting_job, :new_gardening_job, :new_other_job, :create, :show, :jobdispatch]
  before_filter :authenticate_admin_user!, :only => [:jobdispatch]

  def jobdispatch
    @job = Job.find_by_id(params[:id])
    @workers = WorkerProfile.all
    @worker_profile = WorkerProfile.last
  end

  def addworker
  @job = Job.find_by_id(params[:id])
  @worker_profile = WorkerProfile.find_by_id(params[:id])
  @job.worker_profiles << @worker
  respond_to do |format|
    format.html
    format.js
    end
  end

def update
   @job = Job.find_by_id(params[:id])
   @job.worker_profiles << WorkerProfile.where(:first_name => params[:worker_profile][:first_name], :last_name => params[:worker_profile][:last_name])
    if @job.save
     redirect_back
    else
       render :new
    end
end
def new_moving_job
  @job = Job.new(params[:job])
end
def new_painting_job
  @job = Job.new(params[:job])
end
def new_gardening_job
  @job = Job.new(params[:job])
end
def new_other_job
  @job = Job.new(params[:job])
end
def create
  create!(:notice => "Thank you for using the Day Labor Program, we have received your request and will contact you shortly.")
end
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wages_helper.rb
module WagesHelper
end

app/views/admin/jobs/_form.html.haml
= form_for [:admin, @job] do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :kind
    = f.text_field :kind
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :date_of_job
    = f.datetime_select :date_of_job
  .field
    = f.label :duration
    = f.text_field :duration
  .field
    = f.label :address
    = f.text_field :address
  .field
    = f.label :cross_street
    = f.text_field :cross_street
  .field
    = f.label :phone_number
    = f.number_field :phone_number
  .field
    = f.label :phone_kind
    = f.text_field :phone_kind
  .field
    = f.label :referred_by
    = f.text_field :referred_by
  .field
    = f.label :payment
    = f.text_field :payment
  .field
    = f.label :one_time
    = f.check_box :one_time
  .field
    = f.label :on_going
    = f.check_box :on_going
  .field
    = f.label :frequency
    = f.text_field :frequency
  .field
    = f.label :num_of_workers
    = f.number_field :num_of_workers
  .field
    = f.label :english_level
    = f.text_field :english_level
  .field
    = f.label :will_pick_up
    = f.check_box :will_pick_up
  .field
    = f.label :job_status
    = f.text_field :job_status
  .field
    = f.label :dispatcher_id
    = f.number_field :dispatcher_id
  .field
    = f.label :receiver_id
    = f.number_field :receiver_id
  .field
    = f.label :estimate
    = f.check_box :estimate
  .field
    = f.label :estimate_accepted
    = f.check_box :estimate_accepted
  .field
    = f.label :estimate_amount
    = f.text_field :estimate_amount
  .field
    = f.label :employer_profile_id
    = f.number_field :employer_profile_id
  .actions
    = f.submit 'Save'

app/views/jobs/_assignworker.html.haml
%fieldset.col-lg-4
  %legend Assign Workers
  = form_for @job do |f|
    - if @job.errors.any?
      #error_explanation
        %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
        %ul
          - @job.errors.full_messages.each do |msg|
            %li= msg

    %div.col-lg-6
      = label_tag :enter_worker_first_name
      = text_field_tag "worker_profile[first_name]", params[:worker_profile]
    %div.col-lg-6
      = label_tag :enter_worker_last_name
      = text_field_tag "worker_profile[last_name]", params[:worker_profile]
    %div.row
    .actions
      = f.submit 'Save', :class => :button

app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend New Job Request
    %div.col-lg-4
      = f.label :number_of_workers_needed
      = f.number_field :num_of_workers
    %div.col-lg-4
      = f.label :date_of_job
      = f.text_field :date_of_job, :id => "datetimepicker"
    %div.row
    %div.col-lg-6
      = f.label :description
      = f.text_area :description
    %div.row
    %div.col-lg-6
      = f.label :requirements
      = f.text_field :requirement
    %div.col-lg-4
      = f.label :english_level_required
      = f.select :english_level, options_for_select(["Some English","Fluent English","Not necessary"]), :prompt => "Select One"
    %div.row
    %div.col-lg-4
      = f.label :employer_first_name
      = f.text_field :employer_first_name
    %div.col-lg-4
      = f.label :employer_last_name
      = f.text_field :employer_last_name
    %div.row
    %div.col-lg-4
      = f.label :estimated_duration
      = f.text_field :duration
    %div.col-lg-4
      = f.label :address
      = f.text_field :address
    %div.col-lg-4
      = f.label :phone_number
      = f.telephone_field :phone_number, :class => "phone"
    %div.col-lg-4
      = f.label :how_did_you_hear_about_us?
      = f.text_field :referred_by
    %div.col-lg-4
      = f.label :payment
      = f.select :payment, options_for_select(["Cash", "Personal Check", "On the Books (w-4)", "On the Books (1099)", "Other"]), :prompt => "Select One"
    %div.row
    %div.col-lg-4
      = f.label :one_time
      = f.check_box :one_time
    %div.col-lg-4
      = f.label :on_going
      = f.check_box :on_going
    %div.col-lg-4
      = f.label :frequency
      = f.text_field :frequency
    %div.row
    %div.col-lg-4
      = f.label :will_pick_up
      = f.check_box :will_pick_up
    %div.col-lg-4
      = f.label :is_this_an_estimate?
      = f.check_box :estimate
    - if admin_user_signed_in?
      %div.col-lg-4
        = f.label :job_status
        = f.text_field :job_status
      %div.col-lg-4
        = f.label :dispatcher_id
        = f.number_field :dispatcher_id
      %div.col-lg-4
        = f.label :receiver_id
        = f.number_field :receiver_id
      %div.col-lg-4
        = f.label :estimate_accepted
        = f.check_box :estimate_accepted
      %div.col-lg-4
        = f.label :estimate_amount
        = f.text_field :estimate_amount
      %div.col-lg-4
        = f.label :employer_profile_id
        = f.number_field :employer_profile_id
      .actions
        = f.submit 'Save', :class => :button
    - else
      .actions
        = f.submit 'Save', :class => :button

app/views/jobs/_gardening_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend New Gardening Job Request
    %div.employer_section_form
      Employer Info (Step 1/2)
      %div.row
      %div.col-lg-4
        = f.label :employer_first_name
        = f.text_field :employer_first_name
      %div.col-lg-4
        = f.label :employer_last_name
        = f.text_field :employer_last_name
      %div.row
      %div.col-lg-4
        = f.label :estimated_duration
        = f.text_field :duration
      %div.col-lg-4
        = f.label :address
        = f.text_field :address
      %div.col-lg-4
        = f.label :phone_number
        = f.telephone_field :phone_number, :class => "phone"
      %div.col-lg-4
        = f.label :how_did_you_hear_about_us?
        = f.text_field :referred_by
      %div.row
      %a{:href=>"#", :id=>"next_link"}Next
    %div.job_section_form
      Job Info (Step 2/2)
      %div.row
      %div.col-lg-2
        = f.label :number_of_workers
        = f.number_field :num_of_workers
        = f.hidden_field :kind, :value => "Gardening"
      %div.col-lg-4
        = f.label :date_of_job
        = f.text_field :date_of_job, :id => "datetimepicker"
      %div.row
      %div.col-lg-2
        = f.label :truck_needed
        = check_box_tag :truck_needed
      %div.col-lg-2
        = f.label :dumpster_needed
        = check_box_tag :dumpster_needed
      %div.col-lg-4
        = f.label :english_level_required
        = f.select :english_level, options_for_select(["Some English","Fluent English","Not necessary"]), :prompt => "Select One"
      %div.col-lg-4
        = f.label :payment
        = f.select :payment, options_for_select(["Cash", "Personal Check", "On the Books (w-4)", "On the Books (1099)", "Other"]), :prompt => "Select One"
      %div.row
      %div.col-lg-6
        = f.label :description
        = f.text_area :description
      %div.col-lg-6
        = f.label :tools_provided
        = text_area_tag :tools_provided
      %div.col-lg-6
        = f.label :tools_needed
        = text_area_tag :tools_needed
      %div.row
      %div.col-lg-4
        = f.label :one_time
        = f.check_box :one_time
      %div.col-lg-4
        = f.label :pruning?
        = check_box_tag :pruning
      %div.col-lg-4
        = f.label :on_going
        = f.check_box :on_going
      %div.col-lg-4
        = f.label :frequency
        = f.text_field :frequency
      %div.row
      %div.col-lg-4
        = f.label :will_pick_up
        = f.check_box :will_pick_up
      %div.col-lg-4
        = f.label :is_this_an_estimate?
        = f.check_box :estimate
      %div.row
      %a{:href=>"#", :id=>"back_link"}Back
      .actions
        = f.submit 'Save', :class => :button

app/views/jobs/_prefilledform.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend New Job Request
    %div.col-lg-4
      = f.label :number_of_workers_needed
      = f.number_field :num_of_workers
    %div.col-lg-4
      = f.label :date_of_job
      = f.text_field :date_of_job, :id => "datetimepicker"
    / %div.col-lg-4
    /   = f.label :kind
    /   = f.text_field :kind
    %div.row
    %div.col-lg-6
      = f.label :description
      = f.text_area :description
    %div.row
    %div.col-lg-6
      = f.label :requirements
      = f.text_field :requirement
    %div.col-lg-4
      = f.label :english_level_required
      = f.text_field :english_level
    %div.row
    %div.col-lg-4
      = f.label :employer_first_name
      = f.text_field :employer_first_name, :value => current_user.profile.first_name
    %div.col-lg-4
      = f.label :employer_last_name
      = f.text_field :employer_last_name, :value => current_user.profile.last_name
    %div.row
    %div.col-lg-4
      = f.label :duration
      = f.text_field :duration
    %div.col-lg-4
      = f.label :address
      = f.text_field :address, :value => current_user.profile.address
    %div.col-lg-4
      = f.label :cross_street
      = f.text_field :cross_street
    %div.col-lg-4
      = f.label :phone_number
      = f.telephone_field :phone_number, :class => "phone", :value => current_user.profile.cell_phone
    %div.col-lg-4
      = f.label :phone_type
      = f.text_field :phone_kind, :value => "Cell Phone"
    %div.col-lg-4
      = f.label :referred_by
      = f.text_field :referred_by
    %div.col-lg-4
      = f.label :payment
      = f.text_field :payment
    %div.col-lg-4
      = f.label :one_time
      = f.check_box :one_time
    %div.col-lg-4
      = f.label :on_going
      = f.check_box :on_going
    %div.col-lg-4
      = f.label :frequency
      = f.text_field :frequency
    %div.col-lg-4
      = f.label :will_pick_up
      = f.check_box :will_pick_up
    %div.col-lg-4
      = f.label :is_this_an_estimate?
      = f.check_box :estimate
    - if admin_user_signed_in?
      %div.col-lg-4
        = f.label :job_status
        = f.text_field :job_status
      %div.col-lg-4
        = f.label :dispatcher_id
        = f.number_field :dispatcher_id
      %div.col-lg-4
        = f.label :receiver_id
        = f.number_field :receiver_id
      %div.col-lg-4
        = f.label :estimate_accepted
        = f.check_box :estimate_accepted
      %div.col-lg-4
        = f.label :estimate_amount
        = f.text_field :estimate_amount
      %div.col-lg-4
        = f.label :employer_profile_id
        = f.number_field :employer_profile_id
    - else
      .actions
        = f.submit 'Save'

app/views/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
%h1 Listing jobs

%table
  %tr
    %th Kind
    %th Description
    %th Date of job
    %th Duration
    %th Address
    %th Cross street
    %th Phone number
    %th Phone kind
    %th Referred by
    %th Payment
    %th One time
    %th On going
    %th Frequency
    %th Num of workers
    %th English level
    %th Will pick up
    %th Job status
    %th Dispatcher
    %th Receiver
    %th Estimate
    %th Estimate accepted
    %th Estimate amount
    %th Employer profile
    %th
    %th
    %th

  - @jobs.each do |job|
    %tr
      %td= job.kind
      %td= job.description
      %td= job.date_of_job
      %td= job.duration
      %td= job.address
      %td= job.cross_street
      %td= job.phone_number
      %td= job.phone_kind
      %td= job.referred_by
      %td= job.payment
      %td= job.one_time
      %td= job.on_going
      %td= job.frequency
      %td= job.num_of_workers
      %td= job.english_level
      %td= job.will_pick_up
      %td= job.job_status
      %td= job.dispatcher_id
      %td= job.receiver_id
      %td= job.estimate
      %td= job.estimate_accepted
      %td= job.estimate_amount
      %td= job.employer_profile_id
      %td= link_to 'Show', job
      %td= link_to 'Edit', edit_job_path(job)
      %td= link_to 'Destroy', job, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Job', new_job_path

app/views/jobs/jobdispatch.html.haml
%p#notice= notice

%h1 New Job Dispatch
%p.large-7.columns
  %b Employer Name | Nombre del Empleador:
  = @job.employer_first_name + " " + @job.employer_last_name
%p.large-7.columns
  %b Worker | Trabajador(a):
  - if @job.has_workers
    %ul.col-lg-6
      - @job.worker_profiles.each do |worker|
        %li
          = link_to worker.first_name + " " + worker.last_name, worker_profile_path(worker.id)
    = render 'assignworker'
  -else
    %p.large-7.columns You have not assigned any workers yet!
    = render 'assignworker'
  %p.large-7.columns
    %b Type of Job:
    = @job.kind
  %p.large-7.columns
    %b Time and Date of Job:
    = @job.date_of_job
  %p.large-7.columns
    %b Estimated Duration of Job:
    = @job.duration
  %p.large-7.columns
    %b Pay per hour:
    = @job.payment
  %p.large-7.columns
    %b Address:
    = @job.address
  %p.large-7.columns
    %b Cross street:
    = @job.cross_street
  %p.large-7.columns
    %b Phone number:
    = @job.phone_number
  %p.large-7.columns
    %b Phone kind:
    = @job.phone_kind
%div.row
%div#map.large-8.columns
%form#calculate-route.col-lg-4{:action => "#", :method => "get", :name => "calculate-route"}
  %label{:for => "from"} From:
  %input#from{:name => "from", :value => "3358 Cesar Chavez Street, San Francisco CA", :required => "required", :size => "30", :type => "text"}/
  %a#from-link{:href => "#"} Get my position
  %br/
  %label{:for => "to"} To:
  %input#to{:name => "to", :value => @job.address, :required => "required", :size => "30", :type => "text"}/
  %a#to-link{:href => "#"} Get my position
  %br/
  %input{:type => "submit"}/
  %input{:type => "reset"}/
%div.row
%h5.large-7.columns Information for employers about the SF Day Labor Program
%p.large-7.columns
  %b Worker Rights:
%p.large-7.columns DLP job prices are pro-set and non-negotiable.  The pro-set price is on the other side of your paper.  Employers are required by law to pay all workers at least the minimum wage of $8.00/hr in California and $10.55/hr in San Francisco.  Employers may not require workers to endanger themselves in unsafe working conditions.  Employers are financially responsible for medical expenses resulting from an on-the-job injury.  Under California Law, employers must give workers a 30 minute lunch break after 5 hours of work and a paid 10 minute break after each 4 hours of work.
%p.large-7.columns
  %b Payment:
%p.large-7.columns You are responsible for paying the workers.  We are a non-profit organization and do not take a cut of the workers’ pay.  You pay each worker directly, preferably by cash.  IOU’s are adamantly not accepted.
%p.large-7.columns
  %b Immigration status and documentation requirements of the INS:
%p.large-7.columns Under our program policy, we do not ask about the immigration status of the workers who use the Program.  Under federal law, if you are hiring someone for casual domestic work in a private home or if the labor is of a sporadic, irregular, or intermittent basis, you are not required to fill out an 1-9, the INS form that requests information about a worker’s permission to work in the U.S.
%p.large-7.columns
  %b Disclaimer:
%p.large-7.columns The Day Labor Program provides a place for you to meet day laborers.  We are not an employment agency.  We are not responsible for ensuring the qualifications of the day laborers, the quality of the work performed, nor for any other legal responsibility of the employers.
%p.large-7.columns It is up to you and the individual(s) that you contact through the Day Labor Program to decide the terms and conditions of employment and to make sure that you are in compliance with all state and federal laws.
.row
= link_to 'Edit', edit_job_path(@job)
\|
= link_to 'Back', jobs_path

app/views/jobs/jobdispatch.js.erb
// alert("foo");

app/views/jobs/new.html.haml
%h1 Post a new job
- if user_signed_in? && current_user.is_employer
  = render 'prefilledform'
- else
  #modal_window.reveal-modal
  %h3 Please select type of job
  .jobselect.large-5.columns
    %h4 Moving
    %button#moving_select{:data => {"reveal-id" => "modal_window"}}
      Select
  .jobselect.large-5.columns
    %h4 Gardening
    %button#gardening_select{:data => {"reveal-id" => "modal_window"}}
      Select
  .jobselect.large-5.columns
    %h4 Painting
    %button#painting_select{:data => {"reveal-id" => "modal_window"}}
      Select
  .jobselect.large-5.columns
    %h4 Other
    %button#job_select{:data => {"reveal-id" => "modal_window"}}
      Select
  .row
= link_to 'Start Over', new_job_path

app/views/jobs/new_moving_job.coffee.erb
new_job_window = $("#modal_window");
new_job_window.html("<%= j render 'moving_form' %>");

$("#next_link").on click: ->
  $(".employer_section_form").hide "slide"
  setTimeout 300
  $(".job_section_form").show "slide"

$("#back_link").on click: ->
  $(".job_section_form").hide "slide"
  setTimeout 300
  $(".employer_section_form").show "slide"

app/views/jobs/show.html.haml
%p#notice= notice

%p
  %b Kind:
  = @job.kind
%p
  %b Description:
  = @job.description
%p
  %b Date of job:
  = @job.date_of_job
%p
  %b Duration:
  = @job.duration
%p
  %b Address:
  = @job.address
%p
  %b Cross street:
  = @job.cross_street
%p
  %b Phone number:
  = @job.phone_number
%p
  %b Phone kind:
  = @job.phone_kind
%p
  %b Referred by:
  = @job.referred_by
%p
  %b Payment:
  = @job.payment
%p
  %b One time:
  = @job.one_time
%p
  %b On going:
  = @job.on_going
%p
  %b Frequency:
  = @job.frequency
%p
  %b Num of workers:
  = @job.num_of_workers
%p
  %b English level:
  = @job.english_level
%p
  %b Will pick up:
  = @job.will_pick_up
%p
  %b Job status:
  = @job.job_status
%p
  %b Dispatcher:
  = @job.dispatcher_id
%p
  %b Receiver:
  = @job.receiver_id
%p
  %b Estimate:
  = @job.estimate
%p
  %b Estimate accepted:
  = @job.estimate_accepted
%p
  %b Estimate amount:
  = @job.estimate_amount
%p
  %b Employer profile:
  = @job.employer_profile_id

= link_to 'Edit', edit_job_path(@job)
\|
= link_to 'Back', jobs_path