config/routes.rb
Dlp::Application.routes.draw do
  resources :search_suggestions

  devise_for :users, :controllers => {sessions: 'sessions'}
  root :to => 'welcome#index'
  resources :worker_profiles

  get "/new_moving_job" => "jobs#new_moving_job", as: :new_moving_job
  get "/new_painting_job" => "jobs#new_painting_job", as: :new_painting_job
  get "/new_gardening_job" => "jobs#new_gardening_job", as: :new_gardening_job
  get "/new_other_job" => "jobs#new_other_job", as: :new_other_job
  get "/user_sign_up" => "users#new", as: :user_sign_up

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

  match '/jobs/:id/jobdispatch' => 'jobs#jobdispatch', :as => :job_jobdispatch
  match '/jobs/:id/addworker/:id' => 'jobs#addworker', :as => :job_addworker

  resources :users, :only => [:show]
  match "welcome/about" => "welcome#about", :as => :about
  match "welcome/contact" => "welcome#contact", :as => :contact
  match "welcome/faq" => "welcome#faq", :as => :faq
  match "welcome/howtohire" => "welcome#howtohire", :as => :howtohire

  match '/admin/jobs/:id/worker_profiles' => 'admin/jobs#worker_profiles', :as => :admin_job_workers

  # resources :identifications


  # resources :items

  # resources :reviews


  # resources :wages


  resources :jobs


  resources :employer_profiles


  # resources :dues


  # resources :referrals






end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  def dispatches
    Job.where(:dispatcher_id => self.id)
  end

  def receives
    Job.where(:receiver_id => self.id)
  end
end

app/models/due.rb
class Due < ActiveRecord::Base
  attr_accessible :amount, :last_paid, :worker_profile_id

  belongs_to :worker_profile
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :worker_profiles
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name

has_and_belongs_to_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :address, :cross_street, :date_of_job, :description, :dispatcher_id, :duration, :employer_profile_id, :english_level, :estimate, :estimate_accepted, :estimate_amount, :frequency, :job_status, :kind, :num_of_workers, :on_going, :one_time, :payment, :phone_kind, :phone_number, :receiver_id, :referred_by, :will_pick_up, :requirement, :employer_first_name, :employer_last_name
  belongs_to :employer_profile
  belongs_to :dispatcher, :class_name => AdminUser
  belongs_to :receiver, :class_name => AdminUser
  has_and_belongs_to_many :items
  has_and_belongs_to_many :worker_profiles
  has_and_belongs_to_many :wages
  has_one :review


  def has_workers
    !self.worker_profiles.empty?
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :url, :user_id

  belongs_to :user
end

app/models/referral.rb
class Referral < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :name
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :answer1, :answer2, :answer3, :answer4, :answer5, :job_id, :prompt1, :prompt2, :prompt3, :prompt4, :prompt5
belongs_to :job
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :worker_profiles
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :worker_profiles
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :timeoutable, :validatable
    attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_id, :profile_type
  belongs_to :profile, polymorphic: true
  has_many :photos

  def has_profile
    !self.profile_type.nil?
  end

  def has_photos
    !self.photos.empty?
  end

  def is_worker
    self.profile_type == "WorkerProfile"
  end

  def is_employer
    self.profile_type == "EmployerProfile"
  end

  def has_jobs
    !self.profile.jobs.empty?
  end
end

app/models/wage.rb
class Wage < ActiveRecord::Base
  attr_accessible :base_amount, :name, :ot_amount
  has_and_belongs_to_many :jobs
end

app/models/worker_profile.rb
class WorkerProfile < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :home_phone, :cell_phone, :work_phone, :address, :bio, :esl_level, :flyered, :gender, :health_insurance, :own_vehicle, :wait_list, :want_referral
  has_one :user, as: :profile, dependent: :destroy
  has_many :dues
  has_and_belongs_to_many :skills
  has_and_belongs_to_many :tools
  has_and_belongs_to_many :identifications
  has_and_belongs_to_many :training_requests
  has_and_belongs_to_many :issues
  has_and_belongs_to_many :jobs

end

app/controllers/worker_profiles_controller.rb
class WorkerProfilesController < InheritedResources::Base
  def new
    @worker_profile = WorkerProfile.new
  end

  def create
     @worker = WorkerProfile.new(params[:worker_profile])
    if @worker.save
      @user = User.find_by_id(current_user.id)
      @user.update_attributes(:profile_id => @worker.id, :profile_type => "WorkerProfile")
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @worker_profile = WorkerProfile.find_by_id(params[:id])
  end
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wages_helper.rb
module WagesHelper
end

app/helpers/worker_profiles_helper.rb
module WorkerProfilesHelper
end

app/views/worker_profiles/_form.html.haml
= form_for @worker_profile do |f|
  - if @worker_profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@worker_profile.errors.count, "error")} prohibited this worker_profile from being saved:"
      %ul
        - @worker_profile.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend New Member Form
    %div.row
      %div.col-lg-6
        = f.label :first_name
        = f.text_field :first_name
      %div.col-lg-6
        = f.label :last_name
        = f.text_field :last_name
    %div.row
      %div.col-lg-4
        = f.label :home_phone
        = f.telephone_field :home_phone, :class => "phone"
      %div.col-lg-4
        = f.label :cell_phone
        = f.telephone_field :cell_phone, :class => "phone"
      %div.col-lg-4
        = f.label :work_phone
        = f.telephone_field :work_phone, :class => "phone"
    %div.row
      %div.col-lg-12
        = f.label :address
        = f.text_field :address
    / .field
    /   = f.label :gender
    /   = f.text_field :gender
    %div.row
      %div.small-12.columns
        = f.label :bio
        = f.text_area :bio
    %div.row
      %div.col-lg-6
        = f.label :esl_level
        = f.text_field :esl_level
      %div.col-lg-6
        = f.label :wait_list
        = f.number_field :wait_list
    %div.row
      %div.col-lg-4
        = f.label :own_vehicle
        = f.check_box :own_vehicle
      %div.col-lg-4
        = f.label :health_insurance
        = f.check_box :health_insurance
      %div.col-lg-4
        = f.label :want_referral
        = f.check_box :want_referral
    / %div.row
    /   %div.col-lg-12
    /     = f.label :flyered
    /     = f.datetime_select :flyered
    %div.row
      %div.col-lg-12
        .actions
          = f.submit 'Save'

app/views/worker_profiles/edit.html.haml
%h1 Editing worker_profile

= render 'form'

= link_to 'Show', @worker_profile
\|
= link_to 'Back', worker_profiles_path

app/views/worker_profiles/index.html.haml
%h1 Listing worker_profiles

%table
  %tr
    %th Gender
    %th Bio
    %th Esl level
    %th Wait list
    %th Own vehicle
    %th Health insurance
    %th Want referral
    %th Flyered
    %th
    %th
    %th

  - @worker_profiles.each do |worker_profile|
    %tr
      %td= worker_profile.gender
      %td= worker_profile.bio
      %td= worker_profile.esl_level
      %td= worker_profile.wait_list
      %td= worker_profile.own_vehicle
      %td= worker_profile.health_insurance
      %td= worker_profile.want_referral
      %td= worker_profile.flyered
      %td= link_to 'Show', worker_profile
      %td= link_to 'Edit', edit_worker_profile_path(worker_profile)
      %td= link_to 'Destroy', worker_profile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Worker profile', new_worker_profile_path

app/views/worker_profiles/new.html.haml
%h1 Day Laborer New Member Intake Form

= render 'form'

= link_to 'Back', worker_profiles_path

app/views/worker_profiles/show.html.haml
%p#notice= notice
%p
  %b First Name:
  = @worker_profile.first_name
%p
  %b Last Name:
  = @worker_profile.last_name
%p
  %b Gender:
  = @worker_profile.gender
%p
  %b Bio:
  = @worker_profile.bio
%p
  %b Esl level:
  = @worker_profile.esl_level
%p
  %b Wait list:
  = @worker_profile.wait_list
%p
  %b Own vehicle:
  = @worker_profile.own_vehicle
%p
  %b Health insurance:
  = @worker_profile.health_insurance
%p
  %b Want referral:
  = @worker_profile.want_referral
%p
  %b Flyered:
  = @worker_profile.flyered

= link_to 'Edit', edit_worker_profile_path(@worker_profile)
\|
= link_to 'Back', worker_profiles_path