config/routes.rb
Dlp::Application.routes.draw do
  resources :search_suggestions

  devise_for :users, :controllers => {sessions: 'sessions'}
  root :to => 'welcome#index'
  resources :worker_profiles

  get "/new_moving_job" => "jobs#new_moving_job", as: :new_moving_job
  get "/new_painting_job" => "jobs#new_painting_job", as: :new_painting_job
  get "/new_gardening_job" => "jobs#new_gardening_job", as: :new_gardening_job
  get "/new_other_job" => "jobs#new_other_job", as: :new_other_job
  get "/user_sign_up" => "users#new", as: :user_sign_up

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  devise_for :users
  ActiveAdmin.routes(self)

  match '/jobs/:id/jobdispatch' => 'jobs#jobdispatch', :as => :job_jobdispatch
  match '/jobs/:id/addworker/:id' => 'jobs#addworker', :as => :job_addworker

  resources :users, :only => [:show]
  match "welcome/about" => "welcome#about", :as => :about
  match "welcome/contact" => "welcome#contact", :as => :contact
  match "welcome/faq" => "welcome#faq", :as => :faq
  match "welcome/howtohire" => "welcome#howtohire", :as => :howtohire

  match '/admin/jobs/:id/worker_profiles' => 'admin/jobs#worker_profiles', :as => :admin_job_workers

  # resources :identifications


  # resources :items

  # resources :reviews


  # resources :wages


  resources :jobs


  resources :employer_profiles


  # resources :dues


  # resources :referrals






end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me
  def dispatches
    Job.where(:dispatcher_id => self.id)
  end

  def receives
    Job.where(:receiver_id => self.id)
  end
end

app/models/due.rb
class Due < ActiveRecord::Base
  attr_accessible :amount, :last_paid, :worker_profile_id

  belongs_to :worker_profile
end

app/models/employer_profile.rb
class EmployerProfile < ActiveRecord::Base
  attr_accessible  :first_name, :last_name, :home_phone, :cell_phone, :work_phone, :address
  has_one :user, as: :profile, dependent: :destroy
  has_many :jobs
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :worker_profiles
end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :name

has_and_belongs_to_many :jobs
end

app/models/job.rb
class Job < ActiveRecord::Base
  attr_accessible :address, :cross_street, :date_of_job, :description, :dispatcher_id, :duration, :employer_profile_id, :english_level, :estimate, :estimate_accepted, :estimate_amount, :frequency, :job_status, :kind, :num_of_workers, :on_going, :one_time, :payment, :phone_kind, :phone_number, :receiver_id, :referred_by, :will_pick_up, :requirement, :employer_first_name, :employer_last_name
  belongs_to :employer_profile
  belongs_to :dispatcher, :class_name => AdminUser
  belongs_to :receiver, :class_name => AdminUser
  has_and_belongs_to_many :items
  has_and_belongs_to_many :worker_profiles
  has_and_belongs_to_many :wages
  has_one :review


  def has_workers
    !self.worker_profiles.empty?
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :url, :user_id

  belongs_to :user
end

app/models/referral.rb
class Referral < ActiveRecord::Base
  attr_accessible :first_name, :last_name, :name
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :answer1, :answer2, :answer3, :answer4, :answer5, :job_id, :prompt1, :prompt2, :prompt3, :prompt4, :prompt5
belongs_to :job
end

app/models/skill.rb
class Skill < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :worker_profiles
end

app/models/tool.rb
class Tool < ActiveRecord::Base
  attr_accessible :name
  has_and_belongs_to_many :worker_profiles
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :timeoutable, :validatable
    attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_id, :profile_type
  belongs_to :profile, polymorphic: true
  has_many :photos

  def has_profile
    !self.profile_type.nil?
  end

  def has_photos
    !self.photos.empty?
  end

  def is_worker
    self.profile_type == "WorkerProfile"
  end

  def is_employer
    self.profile_type == "EmployerProfile"
  end

  def has_jobs
    !self.profile.jobs.empty?
  end
end

app/models/wage.rb
class Wage < ActiveRecord::Base
  attr_accessible :base_amount, :name, :ot_amount
  has_and_belongs_to_many :jobs
end

app/controllers/employer_profiles_controller.rb
class EmployerProfilesController < InheritedResources::Base
  def new
    @employer_profile = EmployerProfile.new
  end

  def create
     @employer = EmployerProfile.new(params[:employer_profile])
    if @employer.save
      @user = User.find_by_id(current_user.id)
      @user.update_attributes(:profile_id => @employer.id, :profile_type => "EmployerProfile")
      redirect_to root_path
    else
      render :new
    end
  end

  def show
    @employer_profile = EmployerProfile.find_by_id(params[:id])
  end
end

app/helpers/dues_helper.rb
module DuesHelper
end

app/helpers/employer_profiles_helper.rb
module EmployerProfilesHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/tools_helper.rb
module ToolsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wages_helper.rb
module WagesHelper
end

app/views/employer_profiles/_form.html.haml
= form_for @employer_profile do |f|
  - if @employer_profile.errors.any?
    #error_explanation
      %h2= "#{pluralize(@employer_profile.errors.count, "error")} prohibited this employer_profile from being saved:"
      %ul
        - @employer_profile.errors.full_messages.each do |msg|
          %li= msg

  %fieldset
    %legend New Employer Form
    %div.row
      %div.col-lg-6
        = f.label :first_name
        = f.text_field :first_name
      %div.col-lg-6
        = f.label :last_name
        = f.text_field :last_name
    %div.row
      %div.col-lg-4
        = f.label :home_phone
        = f.telephone_field :home_phone, :class => "phone"
      %div.col-lg-4
        = f.label :cell_phone
        = f.telephone_field :cell_phone, :class => "phone"
      %div.col-lg-4
        = f.label :work_phone
        = f.telephone_field :work_phone, :class => "phone"
    %div.row
      %div.col-lg-12
        = f.label :address
        = f.text_field :address

    %div.row
      %div.col-lg-12
        .actions
          = f.submit 'Save'

app/views/employer_profiles/edit.html.haml
%h1 Editing employer_profile

= render 'form'

= link_to 'Show', @employer_profile
\|
= link_to 'Back', employer_profiles_path

app/views/employer_profiles/index.html.haml
%h1 Listing employer_profiles

%table
  %tr
    %th
    %th
    %th

  - @employer_profiles.each do |employer_profile|
    %tr
      %td= link_to 'Show', employer_profile
      %td= link_to 'Edit', edit_employer_profile_path(employer_profile)
      %td= link_to 'Destroy', employer_profile, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Employer profile', new_employer_profile_path

app/views/employer_profiles/new.html.haml
%h1 New Employer Form

= render 'form'

= link_to 'Back', employer_profiles_path

app/views/employer_profiles/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_employer_profile_path(@employer_profile)
\|
= link_to 'Back', employer_profiles_path